# Retrieval Accuracy Benchmark

Runs `AccuracyEvaluator` across all 6 agent variants and saves results.

| # | File | Model | Components |
|---|------|-------|-----------|
| 1 | `llama_api` | llama3.2 | full guide |
| 2 | `llama_api_semantic_retriever` | llama3.2 | semantic |
| 3 | `llama_api_final` | llama3.2 | semantic + date parser + checks |
| 4 | `gpt_api` | gpt-4o-mini | full guide |
| 5 | `gpt_api_semantic_retriever` | gpt-4o-mini | semantic |
| 6 | `gpt_api_final` | gpt-4o-mini | semantic + checks |

## 0. Setup

In [1]:
import os, time
import re
from retrieval_accuracy_test import AccuracyEvaluator

# agent classes
from llama_api                  import FredLLMAgent
from llama_api_semantic_retriever import FredLLMAgent  as FredLLMAgent_semantic
from llama_api_final            import FredLLMAgent    as FredLLMAgent_final
from gpt_api                    import OpenAIFredAgent
from gpt_api_semantic_retriever import OpenAIFredAgent as OpenAIFredAgent_semantic
from gpt_api_final              import OpenAIFredAgent as OpenAIFredAgent_final

base_dir = os.getcwd()

TEST_FILE   = os.path.join(base_dir, "../data/QA_test.json")
LLAMA_DIR   = os.path.join(base_dir, "../files/llama3.2")
GPT_DIR     = os.path.join(base_dir, "../files/gpt-4o-mini")

os.makedirs(LLAMA_DIR, exist_ok=True)
os.makedirs(GPT_DIR,   exist_ok=True)

def make_evaluator(agent) -> AccuracyEvaluator:
    """Inject a pre-built agent into a fresh AccuracyEvaluator."""
    # Use llama3.2 as a dummy model arg — agent is overwritten immediately
    ev = AccuracyEvaluator.__new__(AccuracyEvaluator)
    ev.agent      = agent
    ev.test_cases = []
    ev.load_test_cases(TEST_FILE)
    return ev

def run_and_save(evaluator: AccuracyEvaluator, out_path: str):
    t0 = time.time()
    results = evaluator.run_all_tests()
    print(f"Execution time: {time.time() - t0:.2f}s")
    evaluator.export_results(results, out_path)
    return results

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

SeriesRetriever loaded: 92 series available

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

SeriesRetriever loaded: 92 series available

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

SeriesRetriever loaded: 92 series available

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

SeriesRetriever loaded: 92 series available

In [2]:
res1, res2, res3, res4, res5, res6 = {}, {}, {}, {}, {}, {}

---
## 1. llama_api  (full guide)

In [3]:
ev1     = make_evaluator(FredLLMAgent(model="llama3.2", verbose=False))
res1    = run_and_save(ev1, f"{LLAMA_DIR}/retrieval_eval/llama_api.json")

############################################################
Running 50 test cases...
############################################################

[Test 1/50]

============================================================
Question: What's the current unemployment rate?
Expected series_ids: ['UNRATE']

[Test 2/50]

============================================================
Question: Show me the effective federal funds rate for all of 2023
Expected series_ids: ['FEDFUNDS']

[Test 3/50]

============================================================
Question: How has M2 money supply changed over the past 3 years?
Expected series_ids: ['WM2NS']

[Test 4/50]

============================================================
Question: What were new home sales like in Q2 2021?
Expected series_ids: ['HSN1F']

[Test 5/50]

============================================================
Question: Give me the 10-year treasury yield since the start of 2022
Expected series_ids: ['DGS10']

[Test 6/50]

============================================================
Question: How has the US dollar performed against the euro recently?
Expected series_ids: ['DEXUSEU']

[Test 7/50]

============================================================
Question: What was CPI during 2019?
Expected series_ids: ['CPIAUCSL']

[Test 8/50]

============================================================
Question: How did the VIX index change for the first half of 2020
Expected series_ids: ['VIXCLS']

[Test 9/50]

============================================================
Question: How have US imports from Mexico trended over the past 2 years?
Expected series_ids: ['IMPMX']

[Test 10/50]

============================================================
Question: What was the 30-year mortgage rate in Q3 2023?
Expected series_ids: ['MORTGAGE30US']

[Test 11/50]

============================================================
Question: Show me personal consumption expenditures for 2022
Expected series_ids: ['PCE']

[Test 12/50]

============================================================
Question: What's the yield curve spread looking like lately?
Expected series_ids: ['T10Y2Y']

[Test 13/50]

============================================================
Question: How did total commercial bank credit change from Q1 to Q2 2023?
Expected series_ids: ['TOTBKCR']

[Test 14/50]

============================================================
Question: I'm curious about US exports to Canada over the past 18 months
Expected series_ids: ['EXPCA']

[Test 15/50]

============================================================
Question: What did the Fed's total assets look like in 2021?
Expected series_ids: ['WALCL']

[Test 16/50]

============================================================
Question: How has the producer price index changed since 2020
Expected series_ids: ['PPIACO']

[Test 17/50]

============================================================
Question: What's the personal savings rate been over the last 6 months?
Expected series_ids: ['PSAVERT']

[Test 18/50]

============================================================
Question: How many new building permits were issued in Q4 2022?
Expected series_ids: ['PERMIT']

[Test 19/50]

============================================================
Question: Show me how the Japanese yen to dollar exchange rate changed for all of 2024
Expected series_ids: ['DEXJPUS']

[Test 20/50]

============================================================
Question: What's been happening with loan delinquencies over the past 2 years?
Expected series_ids: ['DALLCACBEP']

[Test 21/50]

============================================================
Question: Show me US GDP for Q3 2022
Expected series_ids: ['GDP']

[Test 22/50]

============================================================
Question: How has the St. Louis financial stress index moved over the past year?
Expected series_ids: ['STLFSI4']

[Test 23/50]

============================================================
Question: What was total construction spending in 2023?
Expected series_ids: ['TTLCONS']

[Test 24/50]

============================================================
Question: I'd like to see the employment-to-population ratio since 2021
Expected series_ids: ['EMRATIO']

[Test 25/50]

============================================================
Question: What was the goods trade balance in Q1 2024?
Expected series_ids: ['BOPGTB']

[Test 26/50]

============================================================
Question: How has business inventory trended over the past 5 years?
Expected series_ids: ['BUSINV']

[Test 27/50]

============================================================
Question: How did the discount rate change for the second half of 2022
Expected series_ids: ['DPCREDIT']

[Test 28/50]

============================================================
Question: What does total consumer credit look like right now?
Expected series_ids: ['TOTALSL']

[Test 29/50]

============================================================
Question: Show me light vehicle sales from Q2 to Q3 2021
Expected series_ids: ['ALTSALES']

[Test 30/50]

============================================================
Question: How has the federal government debt changed over the past decade?
Expected series_ids: ['GFDEBTN']

[Test 31/50]

============================================================
Question: How did unemployment and inflation move together in 2023?
Expected series_ids: ['UNRATE', 'CPIAUCSL']

[Test 32/50]

============================================================
Question: Compare the federal funds rate and 10-year treasury yield over the past 2 years
Expected series_ids: ['FEDFUNDS', 'DGS10']

[Test 33/50]

============================================================
Question: What's the trade balance between the US and China in 2022?
Expected series_ids: ['EXPCH', 'IMPCH']

[Test 34/50]

============================================================
Question: How did personal income and spending change since the start of 2023?
Expected series_ids: ['PI', 'PCE']

[Test 35/50]

============================================================
Question: Show me GDP and GNP side by side for Q1 and Q2 2023
Expected series_ids: ['GDP', 'GNP']

[Test 36/50]

============================================================
Question: How have oil prices and CPI moved together over the past 3 years?
Expected series_ids: ['WTISPLC', 'CPIAUCSL']

[Test 37/50]

============================================================
Question: What happened to bank credit and commercial loans during 2020?
Expected series_ids: ['TOTBKCR', 'BUSLOANS']

[Test 38/50]

============================================================
Question: Compare US exports to Canada and Mexico over the past 18 months
Expected series_ids: ['EXPCA', 'EXPMX']

[Test 39/50]

============================================================
Question: How did consumer sentiment and personal savings rate change in 2022?
Expected series_ids: ['UMCSENT', 'PSAVERT']

[Test 40/50]

============================================================
Question: Show me the M1 and M2 money supply since 2020
Expected series_ids: ['WM1NS', 'WM2NS']

[Test 41/50]

============================================================
Question: How did manufacturing hours and earnings look in Q3 and Q4 2022?
Expected series_ids: ['AWHMAN', 'AHEMAN']

[Test 42/50]

============================================================
Question: Compare federal spending and revenue for all of 2024
Expected series_ids: ['FYONET', 'FYFR']

[Test 43/50]

============================================================
Question: How have the peso and Canadian dollar moved against the USD over the past year?
Expected series_ids: ['DEXMXUS', 'DEXCAUS']

[Test 44/50]

============================================================
Question: What does the housing market look like right now - permits, sales, and mortgage rates?
Expected series_ids: ['PERMIT', 'HSN1F', 'MORTGAGE30US']

[Test 45/50]

============================================================
Question: Give me a snapshot of the labor market: unemployment, workforce size, and employment ratio over the past 2 years
Expected series_ids: ['UNRATE', 'CE16OV', 'EMRATIO']

[Test 46/50]

============================================================
Question: What does GDP stand for and how is it different from GNP?
Expected series_ids: []

[Test 47/50]

============================================================
Question: Which indicators should I look at to get a sense of how tight monetary policy is?
Expected series_ids: []

KeyboardInterrupt:

---
## 2. llama_api_semantic_retriever

In [ ]:
ev2     = make_evaluator(FredLLMAgent_semantic(model="llama3.2", verbose=False))
res2    = run_and_save(ev2, f"{LLAMA_DIR}/retrieval_eval/llama_api_semantic_retriever.json")

############################################################
Running 50 test cases...
############################################################

[Test 1/50]

============================================================
Question: What's the current unemployment rate?
Expected series_ids: ['UNRATE']
  Detected same-day query, expanding to 1 year

[Test 2/50]

============================================================
Question: Show me the effective federal funds rate for all of 2023
Expected series_ids: ['FEDFUNDS']

[Test 3/50]

============================================================
Question: How has M2 money supply changed over the past 3 years?
Expected series_ids: ['WM2NS']

[Test 4/50]

============================================================
Question: What were new home sales like in Q2 2021?
Expected series_ids: ['HSN1F']

[Test 5/50]

============================================================
Question: Give me the 10-year treasury yield since the start of 2022
Expected series_ids: ['DGS10']

[Test 6/50]

============================================================
Question: How has the US dollar performed against the euro recently?
Expected series_ids: ['DEXUSEU']

[Test 7/50]

============================================================
Question: What was CPI during 2019?
Expected series_ids: ['CPIAUCSL']

[Test 8/50]

============================================================
Question: Pull up the VIX index for the first half of 2020
Expected series_ids: ['VIXCLS']

[Test 9/50]

============================================================
Question: How have US imports from Mexico trended over the past 2 years?
Expected series_ids: ['IMPMX']

[Test 10/50]

============================================================
Question: What was the 30-year mortgage rate in Q3 2023?
Expected series_ids: ['MORTGAGE30US']

[Test 11/50]

============================================================
Question: Show me personal consumption expenditures for 2022
Expected series_ids: ['PCE']

[Test 12/50]

============================================================
Question: What's the yield curve spread looking like lately?
Expected series_ids: ['T10Y2Y']

[Test 13/50]

============================================================
Question: How did total commercial bank credit change from Q1 to Q2 2023?
Expected series_ids: ['TOTBKCR']

[Test 14/50]

============================================================
Question: I'm curious about US exports to Canada over the past 18 months
Expected series_ids: ['EXPCA']
  End date 2026-06-30 is in the future, capping to today

[Test 15/50]

============================================================
Question: What did the Fed's total assets look like in 2021?
Expected series_ids: ['WALCL']

[Test 16/50]

============================================================
Question: Show me the producer price index since 2020
Expected series_ids: ['PPIACO']

[Test 17/50]

============================================================
Question: What's the personal savings rate been over the last 6 months?
Expected series_ids: ['PSAVERT']

[Test 18/50]

============================================================
Question: How many new building permits were issued in Q4 2022?
Expected series_ids: ['PERMIT']

[Test 19/50]

============================================================
Question: Give me the Japanese yen to dollar exchange rate for all of 2024
Expected series_ids: ['DEXJPUS']

[Test 20/50]

============================================================
Question: What's been happening with loan delinquencies over the past 2 years?
Expected series_ids: ['DALLCACBEP']

[Test 21/50]

============================================================
Question: Show me US GDP for Q3 2022
Expected series_ids: ['GDP']

[Test 22/50]

============================================================
Question: How has the St. Louis financial stress index moved over the past year?
Expected series_ids: ['STLFSI4']

[Test 23/50]

============================================================
Question: What was total construction spending in 2023?
Expected series_ids: ['TTLCONS']

[Test 24/50]

============================================================
Question: I'd like to see the employment-to-population ratio since 2021
Expected series_ids: ['EMRATIO']

[Test 25/50]

============================================================
Question: What was the goods trade balance in Q1 2024?
Expected series_ids: ['BOPGTB']

[Test 26/50]

============================================================
Question: How has business inventory trended over the past 5 years?
Expected series_ids: ['BUSINV']

[Test 27/50]

============================================================
Question: Pull up the discount rate for the second half of 2022
Expected series_ids: ['DPCREDIT']

[Test 28/50]

============================================================
Question: What does total consumer credit look like right now?
Expected series_ids: ['TOTALSL']
  Detected same-day query, expanding to 1 year

[Test 29/50]

============================================================
Question: Show me light vehicle sales from Q2 to Q3 2021
Expected series_ids: ['ALTSALES']

[Test 30/50]

============================================================
Question: How has the federal government debt changed over the past decade?
Expected series_ids: ['GFDEBTN']

[Test 31/50]

============================================================
Question: How did unemployment and inflation move together in 2023?
Expected series_ids: ['UNRATE', 'CPIAUCSL']

[Test 32/50]

============================================================
Question: Compare the federal funds rate and 10-year treasury yield over the past 2 years
Expected series_ids: ['FEDFUNDS', 'DGS10']

[Test 33/50]

============================================================
Question: What's the trade balance between the US and China in 2022?
Expected series_ids: ['EXPCH', 'IMPCH']

[Test 34/50]

============================================================
Question: How did personal income and spending change since the start of 2023?
Expected series_ids: ['PI', 'PCE']

[Test 35/50]

============================================================
Question: Show me GDP and GNP side by side for Q1 and Q2 2023
Expected series_ids: ['GDP', 'GNP']

[Test 36/50]

============================================================
Question: How have oil prices and CPI moved together over the past 3 years?
Expected series_ids: ['WTISPLC', 'CPIAUCSL']

[Test 37/50]

============================================================
Question: What happened to bank credit and commercial loans during 2020?
Expected series_ids: ['TOTBKCR', 'BUSLOANS']

[Test 38/50]

============================================================
Question: Compare US exports to Canada and Mexico over the past 18 months
Expected series_ids: ['EXPCA', 'EXPMX']

[Test 39/50]

============================================================
Question: How did consumer sentiment and personal savings rate change in 2022?
Expected series_ids: ['UMCSENT', 'PSAVERT']

[Test 40/50]

============================================================
Question: Show me the M1 and M2 money supply since 2020
Expected series_ids: ['WM1NS', 'WM2NS']

[Test 41/50]

============================================================
Question: How did manufacturing hours and earnings look in Q3 and Q4 2022?
Expected series_ids: ['AWHMAN', 'AHEMAN']

[Test 42/50]

============================================================
Question: Compare federal spending and revenue for all of 2024
Expected series_ids: ['FYONET', 'FYFR']

[Test 43/50]

============================================================
Question: How have the peso and Canadian dollar moved against the USD over the past year?
Expected series_ids: ['DEXMXUS', 'DEXCAUS']

[Test 44/50]

============================================================
Question: What does the housing market look like right now - permits, sales, and mortgage rates?
Expected series_ids: ['PERMIT', 'HSN1F', 'MORTGAGE30US']
  Invalid date format, defaulting to past 1 year
  Invalid date format, defaulting to past 1 year
  Invalid date format, defaulting to past 1 year

[Test 45/50]

============================================================
Question: Give me a snapshot of the labor market: unemployment, workforce size, and employment ratio over the past 2 years
Expected series_ids: ['UNRATE', 'CE16OV', 'EMRATIO']

[Test 46/50]

============================================================
Question: What does GDP stand for and how is it different from GNP?
Expected series_ids: []

[Test 47/50]

============================================================
Question: Which indicators should I look at to get a sense of how tight monetary policy is?
Expected series_ids: []

[Test 48/50]

============================================================
Question: Show me Nvidia stock price data for 2024
Expected series_ids: []

[Test 49/50]

============================================================
Question: What does an inverted yield curve signal about the economy?
Expected series_ids: []

[Test 50/50]

============================================================
Question: Give me some economic data
Expected series_ids: []

############################################################
SUMMARY
############################################################
Total tests:        50
Successful:         45
Failed:             5

Breakdown:
  Tool-call tests:      45 (passed: 45)
  Non-tool-call tests:  5 (passed: 0)

Average Scores (successful tests only):
  Series ID:   0.91
  Date Range:  0.84
  Overall:     0.87
############################################################

Execution time: 568.17s

Results exported to files/llama3.2/llama_api_semantic_retriever.json

---
## 3. llama_api_final  (semantic + self-checks + date parser)

In [ ]:
ev3     = make_evaluator(FredLLMAgent_final(model="llama3.2", verbose=False))
res3    = run_and_save(ev3, f"{LLAMA_DIR}/retrieval_eval/llama_api_final.json")

############################################################
Running 50 test cases...
############################################################

[Test 1/50]

============================================================
Question: What's the current unemployment rate?
Expected series_ids: ['UNRATE']

[Test 2/50]

============================================================
Question: Show me the effective federal funds rate for all of 2023
Expected series_ids: ['FEDFUNDS']

[Test 3/50]

============================================================
Question: How has M2 money supply changed over the past 3 years?
Expected series_ids: ['WM2NS']

[Test 4/50]

============================================================
Question: What were new home sales like in Q2 2021?
Expected series_ids: ['HSN1F']

[Test 5/50]

============================================================
Question: Give me the 10-year treasury yield since the start of 2022
Expected series_ids: ['DGS10']

[Test 6/50]

============================================================
Question: How has the US dollar performed against the euro recently?
Expected series_ids: ['DEXUSEU']

[Test 7/50]

============================================================
Question: What was CPI during 2019?
Expected series_ids: ['CPIAUCSL']

[Test 8/50]

============================================================
Question: Pull up the VIX index for the first half of 2020
Expected series_ids: ['VIXCLS']

[Test 9/50]

============================================================
Question: How have US imports from Mexico trended over the past 2 years?
Expected series_ids: ['IMPMX']

[Test 10/50]

============================================================
Question: What was the 30-year mortgage rate in Q3 2023?
Expected series_ids: ['MORTGAGE30US']

[Test 11/50]

============================================================
Question: Show me personal consumption expenditures for 2022
Expected series_ids: ['PCE']

[Test 12/50]

============================================================
Question: What's the yield curve spread looking like lately?
Expected series_ids: ['T10Y2Y']

[Test 13/50]

============================================================
Question: How did total commercial bank credit change from Q1 to Q2 2023?
Expected series_ids: ['TOTBKCR']

[Test 14/50]

============================================================
Question: I'm curious about US exports to Canada over the past 18 months
Expected series_ids: ['EXPCA']

[Test 15/50]

============================================================
Question: What did the Fed's total assets look like in 2021?
Expected series_ids: ['WALCL']

[Test 16/50]

============================================================
Question: Show me the producer price index since 2020
Expected series_ids: ['PPIACO']

[Test 17/50]

============================================================
Question: What's the personal savings rate been over the last 6 months?
Expected series_ids: ['PSAVERT']

[Test 18/50]

============================================================
Question: How many new building permits were issued in Q4 2022?
Expected series_ids: ['PERMIT']

[Test 19/50]

============================================================
Question: Give me the Japanese yen to dollar exchange rate for all of 2024
Expected series_ids: ['DEXJPUS']

[Test 20/50]

============================================================
Question: What's been happening with loan delinquencies over the past 2 years?
Expected series_ids: ['DALLCACBEP']

[Test 21/50]

============================================================
Question: Show me US GDP for Q3 2022
Expected series_ids: ['GDP']

[Test 22/50]

============================================================
Question: How has the St. Louis financial stress index moved over the past year?
Expected series_ids: ['STLFSI4']

[Test 23/50]

============================================================
Question: What was total construction spending in 2023?
Expected series_ids: ['TTLCONS']

[Test 24/50]

============================================================
Question: I'd like to see the employment-to-population ratio since 2021
Expected series_ids: ['EMRATIO']

[Test 25/50]

============================================================
Question: What was the goods trade balance in Q1 2024?
Expected series_ids: ['BOPGTB']

[Test 26/50]

============================================================
Question: How has business inventory trended over the past 5 years?
Expected series_ids: ['BUSINV']

[Test 27/50]

============================================================
Question: Pull up the discount rate for the second half of 2022
Expected series_ids: ['DPCREDIT']

[Test 28/50]

============================================================
Question: What does total consumer credit look like right now?
Expected series_ids: ['TOTALSL']

[Test 29/50]

============================================================
Question: Show me light vehicle sales from Q2 to Q3 2021
Expected series_ids: ['ALTSALES']

[Test 30/50]

============================================================
Question: How has the federal government debt changed over the past decade?
Expected series_ids: ['GFDEBTN']

[Test 31/50]

============================================================
Question: How did unemployment and inflation move together in 2023?
Expected series_ids: ['UNRATE', 'CPIAUCSL']

[Test 32/50]

============================================================
Question: Compare the federal funds rate and 10-year treasury yield over the past 2 years
Expected series_ids: ['FEDFUNDS', 'DGS10']

[Test 33/50]

============================================================
Question: What's the trade balance between the US and China in 2022?
Expected series_ids: ['EXPCH', 'IMPCH']

[Test 34/50]

============================================================
Question: How did personal income and spending change since the start of 2023?
Expected series_ids: ['PI', 'PCE']

[Test 35/50]

============================================================
Question: Show me GDP and GNP side by side for Q1 and Q2 2023
Expected series_ids: ['GDP', 'GNP']

[Test 36/50]

============================================================
Question: How have oil prices and CPI moved together over the past 3 years?
Expected series_ids: ['WTISPLC', 'CPIAUCSL']

[Test 37/50]

============================================================
Question: What happened to bank credit and commercial loans during 2020?
Expected series_ids: ['TOTBKCR', 'BUSLOANS']

[Test 38/50]

============================================================
Question: Compare US exports to Canada and Mexico over the past 18 months
Expected series_ids: ['EXPCA', 'EXPMX']

[Test 39/50]

============================================================
Question: How did consumer sentiment and personal savings rate change in 2022?
Expected series_ids: ['UMCSENT', 'PSAVERT']

[Test 40/50]

============================================================
Question: Show me the M1 and M2 money supply since 2020
Expected series_ids: ['WM1NS', 'WM2NS']

[Test 41/50]

============================================================
Question: How did manufacturing hours and earnings look in Q3 and Q4 2022?
Expected series_ids: ['AWHMAN', 'AHEMAN']

[Test 42/50]

============================================================
Question: Compare federal spending and revenue for all of 2024
Expected series_ids: ['FYONET', 'FYFR']

[Test 43/50]

============================================================
Question: How have the peso and Canadian dollar moved against the USD over the past year?
Expected series_ids: ['DEXMXUS', 'DEXCAUS']

[Test 44/50]

============================================================
Question: What does the housing market look like right now - permits, sales, and mortgage rates?
Expected series_ids: ['PERMIT', 'HSN1F', 'MORTGAGE30US']

[Test 45/50]

============================================================
Question: Give me a snapshot of the labor market: unemployment, workforce size, and employment ratio over the past 2 years
Expected series_ids: ['UNRATE', 'CE16OV', 'EMRATIO']

[Test 46/50]

============================================================
Question: What does GDP stand for and how is it different from GNP?
Expected series_ids: []

[Test 47/50]

============================================================
Question: Which indicators should I look at to get a sense of how tight monetary policy is?
Expected series_ids: []
  Start date later than end date, adjusting to 1 year ago

[Test 48/50]

============================================================
Question: Show me Nvidia stock price data for 2024
Expected series_ids: []

[Test 49/50]

============================================================
Question: What does an inverted yield curve signal about the economy?
Expected series_ids: []

[Test 50/50]

============================================================
Question: Give me some economic data
Expected series_ids: []

############################################################
SUMMARY
############################################################
Total tests:        50
Successful:         45
Failed:             5

Breakdown:
  Tool-call tests:      45 (passed: 45)
  Non-tool-call tests:  5 (passed: 0)

Average Scores (successful tests only):
  Series ID:   0.94
  Date Range:  0.94
  Overall:     0.94
############################################################

Execution time: 621.95s

Results exported to files/llama3.2/llama_api_final.json

---
## 4. gpt_api  (full guide)

In [6]:
ev4     = make_evaluator(OpenAIFredAgent(verbose=False))
res4    = run_and_save(ev4, f"{GPT_DIR}/retrieval_eval/gpt_api.json")

############################################################
Running 50 test cases...
############################################################

[Test 1/50]

============================================================
Question: What's the current unemployment rate?
Expected series_ids: ['UNRATE']

[Test 2/50]

============================================================
Question: Show me the effective federal funds rate for all of 2023
Expected series_ids: ['FEDFUNDS']

[Test 3/50]

============================================================
Question: How has M2 money supply changed over the past 3 years?
Expected series_ids: ['WM2NS']

[Test 4/50]

============================================================
Question: What were new home sales like in Q2 2021?
Expected series_ids: ['HSN1F']

[Test 5/50]

============================================================
Question: Give me the 10-year treasury yield since the start of 2022
Expected series_ids: ['DGS10']

[Test 6/50]

============================================================
Question: How has the US dollar performed against the euro recently?
Expected series_ids: ['DEXUSEU']

[Test 7/50]

============================================================
Question: What was CPI during 2019?
Expected series_ids: ['CPIAUCSL']

[Test 8/50]

============================================================
Question: How did the VIX index change for the first half of 2020
Expected series_ids: ['VIXCLS']

[Test 9/50]

============================================================
Question: How have US imports from Mexico trended over the past 2 years?
Expected series_ids: ['IMPMX']

[Test 10/50]

============================================================
Question: What was the 30-year mortgage rate in Q3 2023?
Expected series_ids: ['MORTGAGE30US']

[Test 11/50]

============================================================
Question: Show me personal consumption expenditures for 2022
Expected series_ids: ['PCE']

[Test 12/50]

============================================================
Question: What's the yield curve spread looking like lately?
Expected series_ids: ['T10Y2Y']

[Test 13/50]

============================================================
Question: How did total commercial bank credit change from Q1 to Q2 2023?
Expected series_ids: ['TOTBKCR']

[Test 14/50]

============================================================
Question: I'm curious about US exports to Canada over the past 18 months
Expected series_ids: ['EXPCA']

[Test 15/50]

============================================================
Question: What did the Fed's total assets look like in 2021?
Expected series_ids: ['WALCL']

[Test 16/50]

============================================================
Question: How has the producer price index changed since 2020
Expected series_ids: ['PPIACO']

[Test 17/50]

============================================================
Question: What's the personal savings rate been over the last 6 months?
Expected series_ids: ['PSAVERT']

[Test 18/50]

============================================================
Question: How many new building permits were issued in Q4 2022?
Expected series_ids: ['PERMIT']

[Test 19/50]

============================================================
Question: Show me how the Japanese yen to dollar exchange rate changed for all of 2024
Expected series_ids: ['DEXJPUS']

[Test 20/50]

============================================================
Question: What's been happening with loan delinquencies over the past 2 years?
Expected series_ids: ['DALLCACBEP']

[Test 21/50]

============================================================
Question: Show me US GDP for Q3 2022
Expected series_ids: ['GDP']

[Test 22/50]

============================================================
Question: How has the St. Louis financial stress index moved over the past year?
Expected series_ids: ['STLFSI4']

[Test 23/50]

============================================================
Question: What was total construction spending in 2023?
Expected series_ids: ['TTLCONS']

[Test 24/50]

============================================================
Question: I'd like to see the employment-to-population ratio since 2021
Expected series_ids: ['EMRATIO']

[Test 25/50]

============================================================
Question: What was the goods trade balance in Q1 2024?
Expected series_ids: ['BOPGTB']

[Test 26/50]

============================================================
Question: How has business inventory trended over the past 5 years?
Expected series_ids: ['BUSINV']

[Test 27/50]

============================================================
Question: How did the discount rate change for the second half of 2022
Expected series_ids: ['DPCREDIT']

[Test 28/50]

============================================================
Question: What does total consumer credit look like right now?
Expected series_ids: ['TOTALSL']

[Test 29/50]

============================================================
Question: Show me light vehicle sales from Q2 to Q3 2021
Expected series_ids: ['ALTSALES']

[Test 30/50]

============================================================
Question: How has the federal government debt changed over the past decade?
Expected series_ids: ['GFDEBTN']

[Test 31/50]

============================================================
Question: How did unemployment and inflation move together in 2023?
Expected series_ids: ['UNRATE', 'CPIAUCSL']

[Test 32/50]

============================================================
Question: Compare the federal funds rate and 10-year treasury yield over the past 2 years
Expected series_ids: ['FEDFUNDS', 'DGS10']

[Test 33/50]

============================================================
Question: What's the trade balance between the US and China in 2022?
Expected series_ids: ['EXPCH', 'IMPCH']

[Test 34/50]

============================================================
Question: How did personal income and spending change since the start of 2023?
Expected series_ids: ['PI', 'PCE']

[Test 35/50]

============================================================
Question: Show me GDP and GNP side by side for Q1 and Q2 2023
Expected series_ids: ['GDP', 'GNP']

[Test 36/50]

============================================================
Question: How have oil prices and CPI moved together over the past 3 years?
Expected series_ids: ['WTISPLC', 'CPIAUCSL']

[Test 37/50]

============================================================
Question: What happened to bank credit and commercial loans during 2020?
Expected series_ids: ['TOTBKCR', 'BUSLOANS']

[Test 38/50]

============================================================
Question: Compare US exports to Canada and Mexico over the past 18 months
Expected series_ids: ['EXPCA', 'EXPMX']

[Test 39/50]

============================================================
Question: How did consumer sentiment and personal savings rate change in 2022?
Expected series_ids: ['UMCSENT', 'PSAVERT']

[Test 40/50]

============================================================
Question: Show me the M1 and M2 money supply since 2020
Expected series_ids: ['WM1NS', 'WM2NS']

[Test 41/50]

============================================================
Question: How did manufacturing hours and earnings look in Q3 and Q4 2022?
Expected series_ids: ['AWHMAN', 'AHEMAN']

[Test 42/50]

============================================================
Question: Compare federal spending and revenue for all of 2024
Expected series_ids: ['FYONET', 'FYFR']

[Test 43/50]

============================================================
Question: How have the peso and Canadian dollar moved against the USD over the past year?
Expected series_ids: ['DEXMXUS', 'DEXCAUS']

[Test 44/50]

============================================================
Question: What does the housing market look like right now - permits, sales, and mortgage rates?
Expected series_ids: ['PERMIT', 'HSN1F', 'MORTGAGE30US']

[Test 45/50]

============================================================
Question: Give me a snapshot of the labor market: unemployment, workforce size, and employment ratio over the past 2 years
Expected series_ids: ['UNRATE', 'CE16OV', 'EMRATIO']

[Test 46/50]

============================================================
Question: What does GDP stand for and how is it different from GNP?
Expected series_ids: []

[Test 47/50]

============================================================
Question: Which indicators should I look at to get a sense of how tight monetary policy is?
Expected series_ids: []

[Test 48/50]

============================================================
Question: Show me Nvidia stock price data for 2024
Expected series_ids: []

[Test 49/50]

============================================================
Question: What does an inverted yield curve signal about the economy?
Expected series_ids: []

[Test 50/50]

============================================================
Question: Give me some economic data
Expected series_ids: []

############################################################
SUMMARY
############################################################
Total tests:        50
Successful:         50
Failed:             0

Breakdown:
  Tool-call tests:      45 (passed: 45)
  Non-tool-call tests:  5 (passed: 5)

Average Scores (successful tests only):
  Series ID:   0.95
  Date Range:  0.96
  Overall:     0.96
############################################################

Execution time: 86.17s

Results exported to files/gpt-4o-mini/retrieval_eval/gpt_api.json

---
## 5. gpt_api_semantic_retriever

In [7]:
ev5     = make_evaluator(OpenAIFredAgent_semantic(verbose=False))
res5    = run_and_save(ev5, f"{GPT_DIR}/retrieval_eval/gpt_api_semantic_retriever.json")

############################################################
Running 50 test cases...
############################################################

[Test 1/50]

============================================================
Question: What's the current unemployment rate?
Expected series_ids: ['UNRATE']

[Test 2/50]

============================================================
Question: Show me the effective federal funds rate for all of 2023
Expected series_ids: ['FEDFUNDS']

[Test 3/50]

============================================================
Question: How has M2 money supply changed over the past 3 years?
Expected series_ids: ['WM2NS']

[Test 4/50]

============================================================
Question: What were new home sales like in Q2 2021?
Expected series_ids: ['HSN1F']

[Test 5/50]

============================================================
Question: Give me the 10-year treasury yield since the start of 2022
Expected series_ids: ['DGS10']

[Test 6/50]

============================================================
Question: How has the US dollar performed against the euro recently?
Expected series_ids: ['DEXUSEU']

[Test 7/50]

============================================================
Question: What was CPI during 2019?
Expected series_ids: ['CPIAUCSL']

[Test 8/50]

============================================================
Question: How did the VIX index change for the first half of 2020
Expected series_ids: ['VIXCLS']

[Test 9/50]

============================================================
Question: How have US imports from Mexico trended over the past 2 years?
Expected series_ids: ['IMPMX']

[Test 10/50]

============================================================
Question: What was the 30-year mortgage rate in Q3 2023?
Expected series_ids: ['MORTGAGE30US']

[Test 11/50]

============================================================
Question: Show me personal consumption expenditures for 2022
Expected series_ids: ['PCE']

[Test 12/50]

============================================================
Question: What's the yield curve spread looking like lately?
Expected series_ids: ['T10Y2Y']

[Test 13/50]

============================================================
Question: How did total commercial bank credit change from Q1 to Q2 2023?
Expected series_ids: ['TOTBKCR']

[Test 14/50]

============================================================
Question: I'm curious about US exports to Canada over the past 18 months
Expected series_ids: ['EXPCA']

[Test 15/50]

============================================================
Question: What did the Fed's total assets look like in 2021?
Expected series_ids: ['WALCL']

[Test 16/50]

============================================================
Question: How has the producer price index changed since 2020
Expected series_ids: ['PPIACO']

[Test 17/50]

============================================================
Question: What's the personal savings rate been over the last 6 months?
Expected series_ids: ['PSAVERT']

[Test 18/50]

============================================================
Question: How many new building permits were issued in Q4 2022?
Expected series_ids: ['PERMIT']

[Test 19/50]

============================================================
Question: Show me how the Japanese yen to dollar exchange rate changed for all of 2024
Expected series_ids: ['DEXJPUS']

[Test 20/50]

============================================================
Question: What's been happening with loan delinquencies over the past 2 years?
Expected series_ids: ['DALLCACBEP']

[Test 21/50]

============================================================
Question: Show me US GDP for Q3 2022
Expected series_ids: ['GDP']

[Test 22/50]

============================================================
Question: How has the St. Louis financial stress index moved over the past year?
Expected series_ids: ['STLFSI4']

[Test 23/50]

============================================================
Question: What was total construction spending in 2023?
Expected series_ids: ['TTLCONS']

[Test 24/50]

============================================================
Question: I'd like to see the employment-to-population ratio since 2021
Expected series_ids: ['EMRATIO']

[Test 25/50]

============================================================
Question: What was the goods trade balance in Q1 2024?
Expected series_ids: ['BOPGTB']

[Test 26/50]

============================================================
Question: How has business inventory trended over the past 5 years?
Expected series_ids: ['BUSINV']

[Test 27/50]

============================================================
Question: How did the discount rate change for the second half of 2022
Expected series_ids: ['DPCREDIT']

[Test 28/50]

============================================================
Question: What does total consumer credit look like right now?
Expected series_ids: ['TOTALSL']

[Test 29/50]

============================================================
Question: Show me light vehicle sales from Q2 to Q3 2021
Expected series_ids: ['ALTSALES']

[Test 30/50]

============================================================
Question: How has the federal government debt changed over the past decade?
Expected series_ids: ['GFDEBTN']

[Test 31/50]

============================================================
Question: How did unemployment and inflation move together in 2023?
Expected series_ids: ['UNRATE', 'CPIAUCSL']

[Test 32/50]

============================================================
Question: Compare the federal funds rate and 10-year treasury yield over the past 2 years
Expected series_ids: ['FEDFUNDS', 'DGS10']

[Test 33/50]

============================================================
Question: What's the trade balance between the US and China in 2022?
Expected series_ids: ['EXPCH', 'IMPCH']

[Test 34/50]

============================================================
Question: How did personal income and spending change since the start of 2023?
Expected series_ids: ['PI', 'PCE']

[Test 35/50]

============================================================
Question: Show me GDP and GNP side by side for Q1 and Q2 2023
Expected series_ids: ['GDP', 'GNP']

[Test 36/50]

============================================================
Question: How have oil prices and CPI moved together over the past 3 years?
Expected series_ids: ['WTISPLC', 'CPIAUCSL']

[Test 37/50]

============================================================
Question: What happened to bank credit and commercial loans during 2020?
Expected series_ids: ['TOTBKCR', 'BUSLOANS']

[Test 38/50]

============================================================
Question: Compare US exports to Canada and Mexico over the past 18 months
Expected series_ids: ['EXPCA', 'EXPMX']

[Test 39/50]

============================================================
Question: How did consumer sentiment and personal savings rate change in 2022?
Expected series_ids: ['UMCSENT', 'PSAVERT']

[Test 40/50]

============================================================
Question: Show me the M1 and M2 money supply since 2020
Expected series_ids: ['WM1NS', 'WM2NS']

[Test 41/50]

============================================================
Question: How did manufacturing hours and earnings look in Q3 and Q4 2022?
Expected series_ids: ['AWHMAN', 'AHEMAN']

[Test 42/50]

============================================================
Question: Compare federal spending and revenue for all of 2024
Expected series_ids: ['FYONET', 'FYFR']

[Test 43/50]

============================================================
Question: How have the peso and Canadian dollar moved against the USD over the past year?
Expected series_ids: ['DEXMXUS', 'DEXCAUS']

[Test 44/50]

============================================================
Question: What does the housing market look like right now - permits, sales, and mortgage rates?
Expected series_ids: ['PERMIT', 'HSN1F', 'MORTGAGE30US']

[Test 45/50]

============================================================
Question: Give me a snapshot of the labor market: unemployment, workforce size, and employment ratio over the past 2 years
Expected series_ids: ['UNRATE', 'CE16OV', 'EMRATIO']

[Test 46/50]

============================================================
Question: What does GDP stand for and how is it different from GNP?
Expected series_ids: []

[Test 47/50]

============================================================
Question: Which indicators should I look at to get a sense of how tight monetary policy is?
Expected series_ids: []

[Test 48/50]

============================================================
Question: Show me Nvidia stock price data for 2024
Expected series_ids: []

[Test 49/50]

============================================================
Question: What does an inverted yield curve signal about the economy?
Expected series_ids: []

[Test 50/50]

============================================================
Question: Give me some economic data
Expected series_ids: []

############################################################
SUMMARY
############################################################
Total tests:        50
Successful:         50
Failed:             0

Breakdown:
  Tool-call tests:      45 (passed: 45)
  Non-tool-call tests:  5 (passed: 5)

Average Scores (successful tests only):
  Series ID:   0.99
  Date Range:  0.97
  Overall:     0.98
############################################################

Execution time: 85.67s

Results exported to files/gpt-4o-mini/retrieval_eval/gpt_api_semantic_retriever.json

---
## 6. gpt_api_final  (semantic + self-checks + date parser)

In [21]:
ev6     = make_evaluator(OpenAIFredAgent_final(verbose=False))
res6    = run_and_save(ev6, f"{GPT_DIR}/retrieval_eval/gpt_api_final.json")

############################################################
Running 50 test cases...
############################################################

[Test 1/50]

============================================================
Question: What's the current unemployment rate?
Expected series_ids: ['UNRATE']

[Test 2/50]

============================================================
Question: Show me the effective federal funds rate for all of 2023
Expected series_ids: ['FEDFUNDS']

[Test 3/50]

============================================================
Question: How has M2 money supply changed over the past 3 years?
Expected series_ids: ['WM2NS']

[Test 4/50]

============================================================
Question: What were new home sales like in Q2 2021?
Expected series_ids: ['HSN1F']

[Test 5/50]

============================================================
Question: Give me the 10-year treasury yield since the start of 2022
Expected series_ids: ['DGS10']

[Test 6/50]

============================================================
Question: How has the US dollar performed against the euro recently?
Expected series_ids: ['DEXUSEU']

[Test 7/50]

============================================================
Question: What was CPI during 2019?
Expected series_ids: ['CPIAUCSL']

[Test 8/50]

============================================================
Question: How did the VIX index change for the first half of 2020
Expected series_ids: ['VIXCLS']

[Test 9/50]

============================================================
Question: How have US imports from Mexico trended over the past 2 years?
Expected series_ids: ['IMPMX']

[Test 10/50]

============================================================
Question: What was the 30-year mortgage rate in Q3 2023?
Expected series_ids: ['MORTGAGE30US']

[Test 11/50]

============================================================
Question: Show me personal consumption expenditures for 2022
Expected series_ids: ['PCE']

[Test 12/50]

============================================================
Question: What's the yield curve spread looking like lately?
Expected series_ids: ['T10Y2Y']

[Test 13/50]

============================================================
Question: How did total commercial bank credit change from Q1 to Q2 2023?
Expected series_ids: ['TOTBKCR']

[Test 14/50]

============================================================
Question: I'm curious about US exports to Canada over the past 18 months
Expected series_ids: ['EXPCA']

[Test 15/50]

============================================================
Question: What did the Fed's total assets look like in 2021?
Expected series_ids: ['WALCL']

[Test 16/50]

============================================================
Question: How has the producer price index changed since 2020
Expected series_ids: ['PPIACO']

[Test 17/50]

============================================================
Question: What's the personal savings rate been over the last 6 months?
Expected series_ids: ['PSAVERT']

[Test 18/50]

============================================================
Question: How many new building permits were issued in Q4 2022?
Expected series_ids: ['PERMIT']

[Test 19/50]

============================================================
Question: Show me how the Japanese yen to dollar exchange rate changed for all of 2024
Expected series_ids: ['DEXJPUS']

[Test 20/50]

============================================================
Question: What's been happening with loan delinquencies over the past 2 years?
Expected series_ids: ['DALLCACBEP']

[Test 21/50]

============================================================
Question: Show me US GDP for Q3 2022
Expected series_ids: ['GDP']

[Test 22/50]

============================================================
Question: How has the St. Louis financial stress index moved over the past year?
Expected series_ids: ['STLFSI4']

[Test 23/50]

============================================================
Question: What was total construction spending in 2023?
Expected series_ids: ['TTLCONS']

[Test 24/50]

============================================================
Question: I'd like to see the employment-to-population ratio since 2021
Expected series_ids: ['EMRATIO']

[Test 25/50]

============================================================
Question: What was the goods trade balance in Q1 2024?
Expected series_ids: ['BOPGTB']

[Test 26/50]

============================================================
Question: How has business inventory trended over the past 5 years?
Expected series_ids: ['BUSINV']

[Test 27/50]

============================================================
Question: How did the discount rate change for the second half of 2022
Expected series_ids: ['DPCREDIT']

[Test 28/50]

============================================================
Question: What does total consumer credit look like right now?
Expected series_ids: ['TOTALSL']

[Test 29/50]

============================================================
Question: Show me light vehicle sales from Q2 to Q3 2021
Expected series_ids: ['ALTSALES']

[Test 30/50]

============================================================
Question: How has the federal government debt changed over the past decade?
Expected series_ids: ['GFDEBTN']

[Test 31/50]

============================================================
Question: How did unemployment and inflation move together in 2023?
Expected series_ids: ['UNRATE', 'CPIAUCSL']

[Test 32/50]

============================================================
Question: Compare the federal funds rate and 10-year treasury yield over the past 2 years
Expected series_ids: ['FEDFUNDS', 'DGS10']

[Test 33/50]

============================================================
Question: What's the trade balance between the US and China in 2022?
Expected series_ids: ['EXPCH', 'IMPCH']

[Test 34/50]

============================================================
Question: How did personal income and spending change since the start of 2023?
Expected series_ids: ['PI', 'PCE']

[Test 35/50]

============================================================
Question: Show me GDP and GNP side by side for Q1 and Q2 2023
Expected series_ids: ['GDP', 'GNP']

[Test 36/50]

============================================================
Question: How have oil prices and CPI moved together over the past 3 years?
Expected series_ids: ['WTISPLC', 'CPIAUCSL']

[Test 37/50]

============================================================
Question: What happened to bank credit and commercial loans during 2020?
Expected series_ids: ['TOTBKCR', 'BUSLOANS']

[Test 38/50]

============================================================
Question: Compare US exports to Canada and Mexico over the past 18 months
Expected series_ids: ['EXPCA', 'EXPMX']

[Test 39/50]

============================================================
Question: How did consumer sentiment and personal savings rate change in 2022?
Expected series_ids: ['UMCSENT', 'PSAVERT']

[Test 40/50]

============================================================
Question: Show me the M1 and M2 money supply since 2020
Expected series_ids: ['WM1NS', 'WM2NS']

[Test 41/50]

============================================================
Question: How did manufacturing hours and earnings look in Q3 and Q4 2022?
Expected series_ids: ['AWHMAN', 'AHEMAN']

[Test 42/50]

============================================================
Question: Compare federal spending and revenue for all of 2024
Expected series_ids: ['FYONET', 'FYFR']

[Test 43/50]

============================================================
Question: How have the peso and Canadian dollar moved against the USD over the past year?
Expected series_ids: ['DEXMXUS', 'DEXCAUS']

[Test 44/50]

============================================================
Question: What does the housing market look like right now - permits, sales, and mortgage rates?
Expected series_ids: ['PERMIT', 'HSN1F', 'MORTGAGE30US']

[Test 45/50]

============================================================
Question: Give me a snapshot of the labor market: unemployment, workforce size, and employment ratio over the past 2 years
Expected series_ids: ['UNRATE', 'CE16OV', 'EMRATIO']

[Test 46/50]

============================================================
Question: What does GDP stand for and how is it different from GNP?
Expected series_ids: []

[Test 47/50]

============================================================
Question: Which indicators should I look at to get a sense of how tight monetary policy is?
Expected series_ids: []

[Test 48/50]

============================================================
Question: Show me Nvidia stock price data for 2024
Expected series_ids: []

[Test 49/50]

============================================================
Question: What does an inverted yield curve signal about the economy?
Expected series_ids: []

[Test 50/50]

============================================================
Question: Give me some economic data
Expected series_ids: []

############################################################
SUMMARY
############################################################
Total tests:        50
Successful:         50
Failed:             0

Breakdown:
  Tool-call tests:      45 (passed: 45)
  Non-tool-call tests:  5 (passed: 5)

Average Scores (successful tests only):
  Series ID:   0.99
  Date Range:  0.97
  Overall:     0.98
############################################################

Execution time: 105.48s

Results exported to files/gpt-4o-mini/retrieval_eval/gpt_api_final.json

---
## 7. Summary comparison

In [19]:
import json

if not res1:
    with open("files/llama3.2/retrieval_eval/llama_api.json") as f:
        res1 = json.load(f)
if not res2:
    with open("files/llama3.2/retrieval_eval/llama_api_semantic_retriever.json") as f:
        res2 = json.load(f)
if not res3:
    with open("files/llama3.2/retrieval_eval/llama_api_final.json") as f:
        res3 = json.load(f)
if not res4:
    with open("files/gpt-4o-mini/retrieval_eval/gpt_api.json") as f:
        res4 = json.load(f)
if not res5:
    with open("files/gpt-4o-mini/retrieval_eval/gpt_api_semantic_retriever.json") as f:
        res5 = json.load(f)
if not res6:
    with open("files/gpt-4o-mini/retrieval_eval/gpt_api_final.json") as f:
        res6 = json.load(f)

In [20]:
import pandas as pd

rows = [
    ("llama_api",                    res1),
    ("llama_api_semantic_retriever", res2),
    ("llama_api_final",              res3),
    ("gpt_api",                      res4),
    ("gpt_api_semantic_retriever",   res5),
    ("gpt_api_final",                res6),
]

records = []
for name, res in rows:
    s = res["summary"]
    records.append({
        "agent":              name,
        "total":              s["total_tests"],
        "passed":             s["successful_tests"],
        "failed":             s["failed_tests"],
        "series_id_score":    s["avg_series_id_score"],
        "date_range_score":   s["avg_date_range_score"],
        "overall_score":      s["avg_overall_score"],
    })

df = pd.DataFrame(records).set_index("agent")
df

,total,passed,failed,series_id_score,date_range_score,overall_score
agent,,,,,,
llama_api,50,45,5,0.75,0.82,0.79
llama_api_semantic_retriever,50,45,5,0.91,0.84,0.87
llama_api_final,50,45,5,0.94,0.94,0.94
gpt_api,50,50,0,0.95,0.96,0.96
gpt_api_semantic_retriever,50,50,0,0.99,0.97,0.98
gpt_api_final,50,50,0,0.99,0.99,0.99

## Checks only and Date Parser only

In [27]:
import json
from datetime import datetime, timedelta


def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def resolve_date(date_spec, is_end=False):
    """Resolve relative date strings (e.g. '1y', '6m', 'today') to YYYY-MM-DD."""
    if not date_spec:
        return ""
    if date_spec == "today":
        return datetime.today().strftime("%Y-%m-%d")
    if date_spec.endswith("y"):
        return (datetime.today() - timedelta(days=365 * int(date_spec[:-1]))).strftime("%Y-%m-%d")
    if date_spec.endswith("m"):
        return (datetime.today() - timedelta(days=30 * int(date_spec[:-1]))).strftime("%Y-%m-%d")
    return date_spec


def compare_dates(date1_str, date2_str, tolerance_days=30):
    """
    Score how well date1 <= date2 (date1 expected earlier).
    Returns 1.0 for exact/within tolerance, 0.0 if date2 < date1.
    """
    if not date1_str or not date2_str:
        return 0.0
    try:
        d1 = datetime.strptime(date1_str, "%Y-%m-%d")
        d2 = datetime.strptime(date2_str, "%Y-%m-%d")
        diff = (d2 - d1).days
        if diff >= 0:
            return max(1.0 - max(diff - tolerance_days, 0) / 100, 0.0)
        else:
            return 0.0
    except ValueError:
        return 0.0


def evaluate_series_id(actual_calls, expected_ids):
    actual_set = {c["series_id"] for c in actual_calls}
    expected_set = set(expected_ids)

    correct = actual_set & expected_set
    precision = len(correct) / len(actual_set) if actual_set else 0.0
    recall = len(correct) / len(expected_set) if expected_set else 1.0
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0

    return {
        "score": round(f1, 4),
        "correct": sorted(correct),
        "missing": sorted(expected_set - actual_set),
        "extra": sorted(actual_set - expected_set),
    }


def evaluate_date_range(actual_calls, expected_date_range, tolerance_days=30):
    if not expected_date_range or not actual_calls:
        return {"score": 1.0, "details": []}

    exp_start = resolve_date(
        expected_date_range.get("relative_start") or expected_date_range.get("start", "")
    )
    exp_end = resolve_date(
        expected_date_range.get("relative_end") or expected_date_range.get("end", ""),
        is_end=True,
    )

    scores, details = [], []
    for call in actual_calls:
        act_start = call.get("start_date", "")
        act_end = call.get("end_date", "")

        # start: actual_start should be <= expected_start (covers early enough)
        start_score = compare_dates(act_start, exp_start, tolerance_days)
        # end: expected_end should be <= actual_end (covers late enough)
        end_score = compare_dates(exp_end, act_end, tolerance_days)

        call_score = (start_score + end_score) / 2
        scores.append(call_score)
        details.append({
            "series_id": call.get("series_id"),
            "actual_start": act_start,
            "expected_start": exp_start,
            "start_score": round(start_score, 4),
            "actual_end": act_end,
            "expected_end": exp_end,
            "end_score": round(end_score, 4),
            "call_score": round(call_score, 4),
        })

    return {
        "score": round(sum(scores) / len(scores), 4),
        "details": details,
    }


def evaluate_case(pred, ground_truth, tolerance_days=30):
    """
    Evaluate one prediction record against its ground truth entry.
    Returns a result dict with series_id and date_range evaluations.
    """
    qid = ground_truth.get("question_id", pred.get("question", "unknown"))
    tool_call_required = ground_truth.get("tool_call_required", True)
    actual_calls = pred.get("tool_calls", [])

    # ── Non-tool-call questions ──────────────────────────────────────────────
    if not tool_call_required:
        made_call = bool(actual_calls)
        return {
            "question_id": qid,
            "question": ground_truth.get("question", ""),
            "tool_call_required": False,
            "success": not made_call,
            "error": "Unexpected tool call made" if made_call else None,
            "series_id_score": 0.0 if made_call else 1.0,
            "date_range_score": 0.0 if made_call else 1.0,
            "overall_score": 0.0 if made_call else 1.0,
        }

    # ── Tool-call questions ──────────────────────────────────────────────────
    if not pred.get("success") or not actual_calls:
        return {
            "question_id": qid,
            "question": ground_truth.get("question", ""),
            "tool_call_required": True,
            "success": False,
            "error": "No tool call extracted",
            "series_id_score": 0.0,
            "date_range_score": 0.0,
            "overall_score": 0.0,
        }

    expected_ids = ground_truth.get("expected_series_ids", [])
    expected_dr = ground_truth.get("expected_date_range", {})

    series_eval = evaluate_series_id(actual_calls, expected_ids)
    date_eval = evaluate_date_range(actual_calls, expected_dr, tolerance_days)
    overall = round(series_eval["score"] * 0.5 + date_eval["score"] * 0.5, 4)

    return {
        "question_id": qid,
        "question": ground_truth.get("question", ""),
        "tool_call_required": True,
        "success": True,
        "actual_calls": actual_calls,
        "series_id_evaluation": series_eval,
        "date_range_evaluation": date_eval,
        "series_id_score": series_eval["score"],
        "date_range_score": date_eval["score"],
        "overall_score": overall,
    }


def run_evaluation(
    pred_path,
    gt_path,
    output_path=None,
    tolerance_days=30,
):
    """
    Args:
        pred_path:   path to QA_test_llama_api_date_only.json (model outputs)
        gt_path:     path to QA_test.json (ground truth with expected_series_ids etc.)
        output_path: optional path to write the result JSON
        tolerance_days: date tolerance window
    """
    preds = load_json(pred_path)
    gts = load_json(gt_path)

    # Build lookup by question text (fallback) or question_id
    gt_by_id = {g.get("question_id"): g for g in gts if "question_id" in g}
    gt_by_q = {g["question"]: g for g in gts}

    results = []
    for pred in preds:
        qid = pred.get("question_id")
        question = pred.get("question", "")
        gt = gt_by_id.get(qid) or gt_by_q.get(question)

        if gt is None:
            results.append({
                "question_id": qid or question,
                "question": question,
                "success": False,
                "error": "No matching ground truth found",
                "overall_score": 0.0,
            })
            continue

        results.append(evaluate_case(pred, gt, tolerance_days))

    # ── Summary ──────────────────────────────────────────────────────────────
    successful = [r for r in results if r["success"]]
    tool_cases = [r for r in results if r.get("tool_call_required", True)]
    non_tool_cases = [r for r in results if not r.get("tool_call_required", True)]

    def avg(lst, key):
        vals = [x[key] for x in lst if key in x]
        return round(sum(vals) / len(vals), 4) if vals else 0.0

    summary = {
        "total": len(results),
        "successful": len(successful),
        "failed": len(results) - len(successful),
        "tool_call_tests": len(tool_cases),
        "tool_call_passed": sum(1 for r in tool_cases if r["success"]),
        "non_tool_call_tests": len(non_tool_cases),
        "non_tool_call_passed": sum(1 for r in non_tool_cases if r["success"]),
        "avg_series_id_score": avg(successful, "series_id_score"),
        "avg_date_range_score": avg(successful, "date_range_score"),
        "avg_overall_score": avg(successful, "overall_score"),
    }

    # Print summary
    sep = "=" * 55
    print(f"\n{sep}")
    print("EVALUATION SUMMARY")
    print(sep)
    print(f"Total tests:           {summary['total']}")
    print(f"Successful:            {summary['successful']}")
    print(f"Failed:                {summary['failed']}")
    print(f"\nBreakdown:")
    print(f"  Tool-call tests:     {summary['tool_call_tests']} "
          f"(passed: {summary['tool_call_passed']})")
    print(f"  Non-tool-call tests: {summary['non_tool_call_tests']} "
          f"(passed: {summary['non_tool_call_passed']})")
    print(f"\nAverage Scores (successful tests only):")
    print(f"  Series ID score:     {summary['avg_series_id_score']}")
    print(f"  Date range score:    {summary['avg_date_range_score']}")
    print(f"  Overall score:       {summary['avg_overall_score']}")
    print(sep)

    output = {"summary": summary, "results": results}

    if output_path:
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(output, f, indent=2, ensure_ascii=False)
        print(f"\nResults saved to: {output_path}")

    return output

In [28]:
res_date_only = run_evaluation(
        pred_path="files/llama3.2/QA_test_llama_api_date_only.json",
        gt_path="data/QA_test.json",
        output_path="files/llama3.2/retrieval_eval/llama_api_date_only.json",
        tolerance_days=30,
    )

=======================================================
EVALUATION SUMMARY
=======================================================
Total tests:           50
Successful:            45
Failed:                5

Breakdown:
  Tool-call tests:     45 (passed: 45)
  Non-tool-call tests: 5 (passed: 0)

Average Scores (successful tests only):
  Series ID score:     0.8407
  Date range score:    0.9444
  Overall score:       0.8926
=======================================================

Results saved to: files/llama3.2/retrieval_eval/llama_api_date_only.json

In [29]:
res_checks_only = run_evaluation(
        pred_path="files/llama3.2/QA_test_llama_api_checks_only.json",
        gt_path="data/QA_test.json",
        output_path="files/llama3.2/retrieval_eval/llama_api_checks_only.json",
        tolerance_days=30,
    )

=======================================================
EVALUATION SUMMARY
=======================================================
Total tests:           50
Successful:            44
Failed:                6

Breakdown:
  Tool-call tests:     45 (passed: 44)
  Non-tool-call tests: 5 (passed: 0)

Average Scores (successful tests only):
  Series ID score:     0.8114
  Date range score:    0.7438
  Overall score:       0.7776
=======================================================

Results saved to: files/llama3.2/retrieval_eval/llama_api_checks_only.json

In [30]:
import pandas as pd

rows = [
    ("llama_api_date_only", res_date_only),
    ("llama_api_checks_only", res_checks_only),
]

records = []
for name, res in rows:
    s = res["summary"]
    records.append({
        "agent":              name,
        "total":              s["total"],
        "passed":             s["successful"],
        "failed":             s["failed"],
        "series_id_score":    s["avg_series_id_score"],
        "date_range_score":   s["avg_date_range_score"],
        "overall_score":      s["avg_overall_score"],
    })

df = pd.DataFrame(records).set_index("agent")
df

,total,passed,failed,series_id_score,date_range_score,overall_score
agent,,,,,,
llama_api_date_only,50,45,5,0.8407,0.9444,0.8926
llama_api_checks_only,50,44,6,0.8114,0.7438,0.7776